[features]
seeds = false
skip-lint = false

[programs.localnet]
move_token = "CpCRu5ziJbffaFLxxY1gQPV2Lpyq8iBecLweZUH8Rngu"
simple_liquidity_pool = "GMDA6SqHUFzctniBczeBSsoLEfd3HaW161wwyAms2buL"

[programs.devnet]
move_token = "CpCRu5ziJbffaFLxxY1gQPV2Lpyq8iBecLweZUH8Rngu"
simple_liquidity_pool = "GMDA6SqHUFzctniBczeBSsoLEfd3HaW161wwyAms2buL"

[registry]
url = "https://api.apr.dev"

# Anchor will using this cluster for anchor cli
[provider]
#cluster = "Localnet"
cluster = "devnet"
wallet = "/Users/macos/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 programs/**/lib.test.ts"
test-program="yarn test-program"
test-only = "yarn test-only"
